# Generated by Django 6.0.6 on 2026-06-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_catagory_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.IntegerField(default=0),
        ),
    ]
