# Generated by Django 6.0.6 on 2026-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('sport', 'sports'), ('cloth', 'cloth'), ('fashion', 'fashion'), ('laptop', 'laptop'), ('pc', 'Computer')]),
        ),
    ]
